version: '3.9'

services:
  portfolio_app:
    build: .
    container_name: portfolio_app
    volumes:
      - .:/app
    working_dir: /app
    command: python main.py
    environment:
      - PYTHONUNBUFFERED=1
    # Optional: expose a port if you later add FastAPI or Flask
    # ports:
    #   - "8000:8000"
